1.
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE numeros [
    <!ELEMENT numeros (#PCDATA)>
]>
<numeros>25</numeros>

2.
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE letras [ 
    <!ELEMENT letras (letra)> 
    <!ELEMENT letra (#PCDATA)> 
]> 

<letras> 
    <letra>m</letra> 
</letras>

3.
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE colores [ 
	<!ELEMENT colores (color*)> 
	<!ELEMENT color (#PCDATA)> 
]> 
 
<colores> 
	<color>azul marino</color> 
	<color>negro</color>
	<color>amarillo</color>
</colores>

4.
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE flores [ 
	<!ELEMENT flores (flor+)> 
	<!ELEMENT flor (#PCDATA)> 
]> 
 
<flores> 
	<flor>Rosa</flor>
</flores>

5.
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE animales [ 
	<!ELEMENT animales (animal*)> 
	<!ELEMENT animal (#PCDATA)> 
]> 

<animales> 
	<animal>Caniche</animal> 
	<animal>Siamés</animal>
</animales>

6.
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE escritores [ 
	<!ELEMENT escritores (escritor*)> 
	<!ELEMENT escritor (nombre, nacimiento)> 
	<!ELEMENT nombre (#PCDATA)> 
	<!ELEMENT nacimiento (#PCDATA)> 
]> 
 
<escritores> 
	<escritor> 
	   <nombre>Mario Vargas Llosa</nombre> 
	   <nacimiento>28 de marzo de 1936</nacimiento> 
	</escritor> 
	<escritor> 
	   <nombre>Milan Kundera</nombre>
	   <nacimiento>1 de abril de 1929</nacimiento> 
	</escritor> 
</escritores>

7.
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE musicos [ 
	<!ELEMENT musicos (musico*)> 
	<!ELEMENT musico ((nombre | apodo), fechaNacimiento)> 
	<!ELEMENT nombre (#PCDATA)> 
	<!ELEMENT apodo (#PCDATA)> 
	<!ELEMENT fechaNacimiento (#PCDATA)> 
]> 
 
<musicos> 
	<musico> 
	   <nombre>Antonio Vivaldi</nombre> 
	   <fechaNacimiento>4 de marzo de 1678</fechaNacimiento> 
	</musico> 
	<musico> 
	   <apodo>El viejo peluca</apodo> 
	   <fechaNacimiento>21 de marzo de 1685</fechaNacimiento> 
	</musico> 
</musicos>

8.
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE agenda [ 
	<!ELEMENT agenda (contacto*)> 
	<!ELEMENT contacto (nombre, telefonoFijo*, telefonoMovil+)> 
	<!ELEMENT nombre (#PCDATA)> 
	<!ELEMENT telefonoFijo (#PCDATA)>
  <!ELEMENT telefonoMovil (#PCDATA)> 
]> 
 
<agenda> 
	<contacto> 
	   <nombre>Ayuntamiento</nombre> 
	   <telefonoFijo>010</telefonoFijo> 
	   <telefonoMovil>No disponible</telefonoMovil>
	</contacto> 
	<contacto> 
	   <nombre>Emergencias</nombre> 
	   <telefonoFijo>112 (Unión Europea)</telefonoFijo> 
	   <telefonoFijo>911 (Estados Unidos)</telefonoFijo> 
	   <telefonoMovil>Desconocido</telefonoMovil> 
	</contacto>
</agenda>

9.
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE sistemaSolar [ 
	<!ELEMENT sistemaSolar (cuerpo*)> 
	<!ELEMENT cuerpo (planeta | satelite | asteroide)> 
	<!ELEMENT planeta (#PCDATA)> 
	<!ELEMENT satelite (#PCDATA)> 
	<!ELEMENT asteroide (#PCDATA)> 
]> 
 
<sistemaSolar> 
	<cuerpo> 
	   <satelite>Luna</satelite>
	</cuerpo>
	<cuerpo> 
	   <asteroide>Ceres</asteroide> 
	</cuerpo> 
</sistemaSolar>
